### PR TITLE
Update React & Radium

### PR DESCRIPTION
**Pull request by kylecesmat**
- Upgraded dependencies
- Fixed warnings about unitless values. Style properties passed to react that are `0` will no longer have `px` appended to them per https://github.com/facebook/react/pull/5140
- Fixed warnings about `xmlns` being applied to an `<svg>` tag. Some warnings still exist but are related to this https://github.com/FormidableLabs/formidable-landers/blob/54729c0f2be80c7ecbe4c8d5e6ebccd3ed91dbe6/src/assets/logos.jsx#L4

### CODE REVIEW

**Comment by kylecesmat** [comment]
cc @coopy

**Comment by kylecesmat** [comment]
Also, I believe this fixes #3 - I could not reproduce any issue, perhaps the latest radium upgrade fixes whatever problem was occurring?

**Comment by coopy** [comment]
@paulathevalley assigning to you!

**Comment by paulathevalley** [comment]
It's perfect! :rocket:

**Pull request merged**
