### PR TITLE
Update Favicon

### PR DESCRIPTION
**Pull request by paulathevalley**
* Update favicon to have a transparent background
* Generate favicons for all browsers

### CODE REVIEW

**Comment by paulathevalley** [comment]
@beccalee123 I didn’t update `index.html` which I think is what's used in dev... it’s been awhile. :( Try again!

**Comment by beccalee123** [comment]
Still not seeing them. I did `git pull` and `npm install` before trying to run it again, but no luck.

**Comment by paulathevalley** [comment]
ok troubleshootin’ time. did you clear your cache? if that doesn’t work, can you check the current path of the favicon? it should be /static/favicon/favicon.ico ...and if you open http://localhost:3000/static/favicon/favicon.ico does that file have a transparent background?

**Comment by beccalee123** [comment]
Ooooooooh. Apparently when you go to http://localhost:3000/webpack-dev-server/ you _can't_ see the favicon, whereas when you go to http://localhost:3000/ you can! Sorry about that- TIL!

LGTM!

**Pull request merged**
