### PR TITLE
Task: Apply one thin coat of design polish

### PR DESCRIPTION
**Pull request by paulathevalley**
This PR: 
- Replaces the large `.gif` with smaller video files (`.mp4` & `.webm`)... I think the quality of the movement improved significantly, as well, it’s much smoother
- Visually differentiate the Get Started with Spectacle button 
- Adjusted the demo video to have less slides, large text (except for the list items slides), so it cycles through faster... @kylecesmat this is starting to act more like content for me, but I’d love to know how you see it  

screen shot 2016-10-20 at 10 30 44 am

### CODE REVIEW

**Comment by ebrillhart** [comment]
LGTM!

**Comment by kylecesmat** [comment]
Do you have a gif that we could preview without pulling it down? One note I have, is at quick glance the white & purple buttons look like a form to me. I think three button colors might be a lot here, maybe have them both be purple? Or one be transparent?

**Comment by kylecesmat** [comment]
But it looks great and I think you can :shipit:

**Comment by kylecesmat** [comment]
lgtm

**Comment by paulathevalley** [comment]
@kylecesmat : 
preview

THE BUTTONS MUST BE PERFECT!! cannot ship until so! :thinking:

**Comment by paulathevalley** [comment]
Switched back to the dark button... feeling stuck :sweat: so going to poop it out for now :boat: 

screen shot 2016-10-20 at 11 22 43 am

**Pull request merged**
